
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/lager"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-incubator/cf-test-helpers"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-incubator/credhub-cli"

[[constraint]]
  name = "github.com/cloudfoundry/noaa"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/sonde-go"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/craigfurman/herottp"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/pivotal-cf/brokerapi"

[[constraint]]
  name = "github.com/pivotal-cf/on-demand-services-sdk"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/totherme/unstructured"

[[constraint]]
  name = "github.com/urfave/negroni"
  revision = "e0e50f7dc431c043cb33f91b09c3419d48b7cff5"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/cloudfoundry/bosh-cli"
  version = "2.0.45"

[[override]]
  name = "github.com/cheggaaa/pb"
  version = "=1.0.18"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"
